"""empty message

Revision ID: 6aa72c4e5b4c
Revises: 
Create Date: 2020-03-04 14:23:58.289420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa72c4e5b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_images',
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('image_data', sa.String(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('bottom_left_corner', sa.String(), nullable=True),
    sa.Column('image_rotation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('image_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_images')
    # ### end Alembic commands ###
