"""empty message

Revision ID: 7953a2dd0a0e
Revises: fbbfcdbf2926
Create Date: 2020-03-14 14:53:47.759089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7953a2dd0a0e"
down_revision = "fbbfcdbf2926"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_points",
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.Column("point_location", sa.String(), nullable=False),
        sa.Column("point_name", sa.String(), nullable=False),
        sa.Column("point_desc", sa.String(), nullable=False),
        sa.Column("point_image", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("point_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_points")
    # ### end Alembic commands ###
