"""empty message

Revision ID: b3fb373a508f
Revises: 205f8489bc68
Create Date: 2020-03-27 11:55:14.460629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fb373a508f'
down_revision = '205f8489bc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_models',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_location', sa.String(), nullable=True),
    sa.Column('model_rotation', sa.String(), nullable=True),
    sa.Column('model_scaling', sa.String(), nullable=True),
    sa.Column('model_data', sa.String(), nullable=True),
    sa.Column('model_offset', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_models')
    # ### end Alembic commands ###
