"""empty message

Revision ID: e83f7e172cb3
Revises: 6aa72c4e5b4c
Create Date: 2020-03-05 14:26:52.789505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83f7e172cb3'
down_revision = '6aa72c4e5b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_images', sa.Column('km_height', sa.Float(), nullable=True))
    op.add_column('map_images', sa.Column('km_width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_images', 'km_width')
    op.drop_column('map_images', 'km_height')
    # ### end Alembic commands ###
