"""empty message

Revision ID: fbbfcdbf2926
Revises: 
Create Date: 2020-03-10 14:38:53.297092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbfcdbf2926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_bounds',
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('top_left', sa.String(), nullable=True),
    sa.Column('bottom_right', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('map_name')
    )
    op.create_table('map_images',
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('image_data', sa.String(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('bottom_left_corner', sa.String(), nullable=True),
    sa.Column('image_rotation', sa.Float(), nullable=True),
    sa.Column('km_width', sa.Float(), nullable=True),
    sa.Column('km_height', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('image_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_images')
    op.drop_table('map_bounds')
    # ### end Alembic commands ###
